services:
  todo-db:
    image: mysql:latest
    container_name: movie-db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - movie-db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  movie-db:
    driver: local
